---
title: "Software for Math 4MB"
author: "Ben Bolker, Kenneth Moyle, David Earn"
date: '`r format(Sys.time(),"%d %b %Y")`'
output:
  html_document:
    toc: true
---

## Software used for this course (quick start)

- LaTeX ([downloads](https://www.latex-project.org/get/): get MacTeX for MacOS or MikTeX for Windows)
- Programming languages/interfaces: Python **or** R
   - install and run on your own computer
       - R (and the RStudio IDE) (downloads: [R](https://cloud.r-project.org/), [RStudio desktop](https://rstudio.com/products/rstudio/download/)) **or**
       - Python and Jupyter notebooks (recommended distribution: [Anaconda](https://www.anaconda.com/products/individual))
- Cloud options
   - [Syzygy](mcmaster.syzygy.ca): log in with your McMaster userid/password; access to Jupyter notebooks running R or Python
   - [RStudio cloud](https://rstudio.cloud/): free account allows 15 hours of computation/month (probably? enough for this course) on a web-based RStudio instance
   - most of this software is available on math & stats department servers, but you will need to work in command-line mode *or* install software to allow graphical communication via the X11 system
- (possibly) XPPAUT, a phase-plane/bifurcation analysis tool
- (strongly recommended) A spell-checker that understands LaTeX

## R

- [R](http://www.r-project.org) is an open-source programming language that you can download and install on any computer (it is installed already on all the grad student workstations in the math department).  Installing R gives you the language interpreter and a simple interactive shell.
- [RStudio](https://www.rstudio.com/products/rstudio/) is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management.

## Python

- Python is another open-source programming language
- Jupyter notebooks are a "notebook interface" that facilitates interactive use of Python (or R!)

## LaTeX

The standard system for mathematical typesetting.  You must use it for your assignments, final project and presentations.   

There are several distributions of TeX but [TeXLive](https://www.tug.org/texlive/) has the advantage of having both Windows and OS X versions and including good TeX/LaTeX editors (TeX is a typesetting program and does not itself include an editor).

## Installation & Configuration Notes for LaTeX

### Windows
* the installation can easily take 30 to 60 minutes
* just download and run the `install-tl.exe` file

### OS X
* [https://www.tug.org/mactex/ MacTeX] is a bundle of TeXLive plus TeXShop (a very good editor) and a number of tools.

## Spell-checkers and word counters

- RStudio has built-in LaTeX-aware word counters (`Edit > Word count`) and spell-checkers (ABC-check icon or via Edit menu)
- Jupyter notebooks: if you execute these commands in a code cell of a notebook:

```
!pip install --user jupyter_contrib_nbextensions >/dev/null
!~/.local/bin/jupyter-contrib-nbextension install --user 2>/dev/null
!jupyter nbextension enable spellchecker/main
```

it will enable a (fairly crude) spell-checker extension for your notebooks

There are a number of [spell-checkers that understand LaTeX](http://en.wikibooks.org/wiki/LaTeX/Tips_and_Tricks#Spell-checking_and_Word_Counting), for example:

* ispell
* aspell
* hunspell

All of these run on Macs via the Terminal.

The unix `wc` command can be used to count words in a plain text file.  To use it, you first need to remove the TeX macros from your file.  You can then pipe the output into wc.  For example, from the terminal window on a Mac you can type
```
detex filename | wc
```
where you need to insert the _filename_ of the file in question.

If you have a Mac, the `texcount` command is much more helpful than the above.  The command line syntax is
```
texcount filename
```
after which helpful information is spewed on your screen.



## XPPAUT (numerical analysis of dynamical systems)

XPPAUT is a powerful program for exploration and bifurcation analysis of dynamical systems.  It is already installed on all of the linux workstations in the math department (which you can log into remotely, as well as from the console).  More importantly, it is open-source software, which can be downloaded and installed on any computer.

Some online resources:

* [XPPAUT home page](http://www.math.pitt.edu/~bard/xpp/xpp.html) (where you can download the source code and/or pre-compiled executables)
* Bard Ermentrout's [book on XPPAUT](https://www.amazon.ca/exec/obidos/ASIN/0898715067/)
* Bard Ermentrout's [XPPAUT scholarpedia page](http://www.scholarpedia.org/article/XPPAUT)
* [XPP online help](http://www.math.pitt.edu/~bard/xpp/help/xpphelp.html)

See [Using XPPAUT on a Mac](using_XPPAUT_on_a_mac.md) for help with installing and using XPPAUT under OS X.

Note that XPPAUT does not incorporate the latest version of AUTO, which continues to be developed on its own.  However, AUTO is much harder to use directly than via XPPAUT.
If you do want to use AUTO directly then you can find the latest version to download via the main [AUTO web page](http://cmvl.cs.concordia.ca/auto/).

XPPAUT has limited graphical capabilities, but it is always possible to save output data to a file and use R to create high-quality graphs

### Installation & Configuration Notes

### Windows

* XPPAUT uses X11 graphics which are not native to Windows
** I recommend MobXterm Personal Edition (which is free): http://mobaxterm.mobatek.net/download.html
* Note that XPP expects you to copy the folder xppall from the xppwin.zip file to C:\.
* Some people have had trouble when browsing to a directory in XPP, particularly going up by clicking "..".  I've created an alternate xpp.bat file which you can download to your desktop and use to run xpp; it will cause xpp to use the folder C:\xppall as the default starting location.  You should copy any new .ode files to this folder if you find that browsing up causes xpp to hang.

### Mac OS X
* create a folder in /Applications called XPP
* copy the contents of the XPP disk image to that folder
* run `xpp` like so 
   *  open `Applications -> Utilities -> Terminal` and run "/Applications/xpp/bin/xppaut filename.ode"
   * ... or ...
   * click `command-space` and enter `xppaut`

### Testing your installation

After installing XPPAUT, you should be able to explore the SIR model using [[Media:SIR.ode|this XPPAUT sample .ode file]].  To get started put `SIR.ode` in the folder where you want to work and (assuming you're working from the command line) type
```
xppaut SIR.ode
```
then click the _phaseflow_ button and hit `RETURN`.  You should then see a sensible phase portrait.  If you're not working from the command line then start XPPAUT and load `SIR.ode`.


## Tools for online collaboration on documents and code

- [GitHub](https://github.com/)
    - collaboration on anything, with superb version control
	- similar systems: Gitlab, Bitbucket
- [Dropbox](https://www.dropbox.com/)
    - very simple and convenient, but less-than-superb version control
- Google Drive
- [MacDrive](https://macdrive.mcmaster.ca/accounts/login/?next=/) (you can download & install a client for [Seafile](https://www.seafile.com/en/download/), that will mirror MacDrive folders to your disk)
- [Overleaf](https://www.overleaf.com/): online collaborative LaTeX editing

